apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: firelink-template
parameters:
- name: IMAGE
  description: Image name
  required: true
- name: IMAGE_TAG
  description: Image tag
  required: true
- name: ENV_NAME
  description: ClowdEnvironment name
  required: true

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: firelink-backend
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: service
      replicas: 1 
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        env: 
          - name: OC_SERVER
            valueFrom:
              secretKeyRef:
                name: crc-eph-bot-account
                key: oc-login-server
          - name: OC_TOKEN
            valueFrom:
              secretKeyRef:
                name: crc-eph-bot-account
                key: oc-login-token
          - name: APP_INTERFACE_BASE_URL
            valueFrom:
              secretKeyRef:
                name: firelink-graphql-creds
                key: APP_INTERFACE_BASE_URL
          - name: APP_INTERFACE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: firelink-graphql-creds
                key: APP_INTERFACE_PASSWORD
          - name: APP_INTERFACE_USERNAME
            valueFrom:
              secretKeyRef:
                name: firelink-graphql-creds
                key: APP_INTERFACE_USERNAME
      webServices:
        public:
          enabled: True
          apiPaths: 
            - /api/firelink/
          whitelistPaths:
            - /health
            - /api/firelink/*


