apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdEnvironment
metadata:
  name: firelink
spec:
  targetNamespace: firelink
  providers:
    web:
      port: 8000
      mode: operator
    metrics:
      port: 9000
      mode: operator
      path: "/metrics"
    kafka:
      mode: none
    db:
      mode: none
    logging:
      mode: none
    objectStore:
      mode: none
    inMemoryDb:
      mode: none
    pullSecrets:
    - name: quay-cloudservices-pull
      namespace: ephemeral-base
  resourceDefaults:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 30m
      memory: 512Mi